# Generated by Django 5.0.3 on 2024-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.TextField(max_length=255)),
                ('especie', models.TextField(max_length=255)),
            ],
        ),
    ]
